### ISSUE TITLE
IRQ information parsed as kernel modules

### ISSUE THREAD

**Issue by mmilata** [abrt/satyr#216]
https://bugzilla.redhat.com/show_bug.cgi?id=1189292

**Comment by arhledvink** [comment]
satyr
kern+debug
irq event stamp
./tests/koops_stacktrace.at
lib/koops_stacktrace.c

**Comment by jfilak** [comment]
Fixed in commit 0b3364a63e95d1eb2bf44dcff7ecf38fdb071bb0 which misses a test which could look like the following patch:

```
diff --git a/tests/koops_stacktrace.at b/tests/koops_stacktrace.at
index a2296ec..da1d8db 100644
--- a/tests/koops_stacktrace.at
+++ b/tests/koops_stacktrace.at
@@ -71,6 +71,9 @@ main(void)
     check(true, "Modules linked in: vfat fat\n usb_storage [last unloaded: scsi_wait_scan]\n",
           modules);
 
+    check(true, "Modules linked in: vfat fat\n usb_storage\nirq event stamp: 754336\n",
+          modules);
+
     check(true,
           "Modules linked in: vfat fat usb_storage\n"
           "Pid: 31337, comm: ksoftirqd/2\n",
```

**Comment by jfilak** [comment]
Correction, the commit was included in a pull request with a commit adding the problematic oops to the test set but the linkage between the oops and the bug in the koops modules parser was not clear to me. We should add the direct test mentioned in my previous comment.

```
$ ./autogen.sh && ./configure && make
$ cd tests
- Patch the file
$ rm testsuite
$ make testsuite
$ ./testsuite 75
``

**Comment by arhledvink** [comment]
it's test 74 not 75

**Comment by jfilak** [comment]
The suggested was added in #246

**Comment by xsuchy** [comment]
So closing.
