### ISSUE TITLE
Crash when parsing invalid JSON

### ISSUE THREAD

**Issue by mgrabovsky** [abrt/satyr#285]
Satyr's JSON parser segfaults when trying to parse the simple input `]`.

The problem lies in https://github.com/abrt/satyr/blob/ba0dc050df7803cf119c28f9db6963a9a1aeee4e/lib/json.c#L359 where `top` is dereferenced before being assigned a meaningful value.

Discovered with the help of [american fuzzy lop](http://lcamtuf.coredump.cx/afl/).

**Comment by ernestask** [comment]
The entire parser should be updated. It’s a copy of an ages-old version of https://github.com/udp/json-parser.

**Comment by mgrabovsky** [comment]
That's what I was thinking, too.
