### ISSUE TITLE
git repo does not contain ./satyr-version

### ISSUE THREAD

**Issue by kloczek** [abrt/satyr#296]
By this is not possible to download tar ball from tag and use it.

That tar (current one https://github.com/abrt/satyr//archive/0.29/satyr-0.29.tar.gz) is not with git data.

Suggestion: remove autogen.sh content replace it with one command "autoreconf -fiv". After remove many lines in Makefile.am all what it would be necessary is maintain version in first line of the configure.ac.

**Comment by kloczek** [comment]
Here is example what can be done.
[satyr-simplifications.patch.txt](https://github.com/abrt/satyr/files/3874815/satyr-simplifications.patch.txt)

**Comment by ernestask** [comment]
Not sure what you’re doing, but that tarball is literally what you get from git-archive. I’m not exactly inclined to generate distribution ones and upload them by hand every time.

**Comment by ernestask** [comment]
The versioning will also stay as-is until we can move to Meson and simplify things even more.

**Comment by kloczek** [comment]
I have implemented build procedure which does not rely on you tar balls generated by dist/distcheck targets. This allows me to build satyr package using any point of commit.
