### ISSUE TITLE
configure doesn't check for elfutils

### ISSUE THREAD

**Issue by yurivict** [abrt/satyr#326]

**Comment by michalfabik** [comment]
Hi, could you please provide a few more details as to what exactly the issue is? The `elfutils` package only provides binaries and satyr doesn't use any of those. We're checking for `libdw` which is provided by `elfutils-devel`. Perhaps you need the check for `elfutils-devel` to be explicit for some reason?

**Comment by mzidek-gh** [comment]
If this caused some error during build the logs would be useful so we know exactly what the issues is.

**Comment by michalfabik** [comment]
What system are you building on?

**Comment by yurivict** [comment]
FreeBSD.

**Comment by yurivict** [comment]
```elfutils``` is a separate package.

**Comment by michalfabik** [comment]
Hi @yurivict, please see the PR above. I'm not quite sure what exactly it was that you needed to check for. IIRC, you were talking about an elfutils header but you edited the message in the meantime. I added a check for `elfutils/version.h`, since that's a header we're including from satyr code.

**Comment by yurivict** [comment]
configure should check that elfutils is installed. I ran configure - it succeeded. Thenn I ran build, and it failed because elfutils was missing. This is a bug IMO.

**Comment by michalfabik** [comment]
Could you please paste the output from the build?  
  
On Linux, the `elfutils` package only contains the following:  
  
`$ rpm -ql elfutils
/usr/bin/eu-addr2line
/usr/bin/eu-ar
/usr/bin/eu-elfclassify
/usr/bin/eu-elfcmp
/usr/bin/eu-elfcompress
/usr/bin/eu-elflint
/usr/bin/eu-findtextrel
/usr/bin/eu-make-debug-archive
/usr/bin/eu-nm
/usr/bin/eu-objdump
/usr/bin/eu-ranlib
/usr/bin/eu-readelf
/usr/bin/eu-size
/usr/bin/eu-stack
/usr/bin/eu-strings
/usr/bin/eu-strip
/usr/bin/eu-unstrip
$`  
  
And we aren't using any of those binaries. It would be good to know what specifically from the `elfutils` package you're missing. Or is there a way to check for a rpm (or whatever package management system) package with Autotools?
